-- GTA6Trucos: dynamic news layer
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  slug_es text not null unique,
  slug_en text not null unique,
  title_es text not null,
  title_en text not null,
  excerpt_es text,
  excerpt_en text,
  content_es text not null,
  content_en text not null,
  image text,
  category text not null default 'GTA VI',
  tags text[] default '{}',
  source_name text,
  source_url text,
  published_at timestamptz not null default now(),
  published boolean not null default false,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists news_published_date_idx on public.news (published, published_at desc);
create index if not exists news_slug_es_idx on public.news (slug_es);
create index if not exists news_slug_en_idx on public.news (slug_en);

alter table public.news enable row level security;
drop policy if exists "Public can read published news" on public.news;
create policy "Public can read published news" on public.news for select using (published = true);

create or replace function public.touch_news_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists news_updated_at on public.news;
create trigger news_updated_at before update on public.news for each row execute function public.touch_news_updated_at();
